apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-postgres-sink
  namespace: kafka-connect
data:
  postgres-sink-connector.json: |
    {
      "name": "postgres-sink-connector",
      "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
        "topics": "testtopic",
        "connection.url": "jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/camunda",
        "connection.user": "camunda",
        "connection.password": "camunda",
        "auto.create": "true",
        "insert.mode": "insert",
        "pk.mode": "none",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter"
      }
    }
  keycloak-cdc-connector.json: |
    {
      "name": "keycloak-cdc-connector",
      "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "tasks.max": "1",
        "database.hostname": "postgresql.postgresql.svc.cluster.local",
        "database.port": "5432",
        "database.user": "postgres",
        "database.password": "postgres",
        "database.dbname": "keycloak",
        "topic.prefix": "keycloakdb",
        "plugin.name": "pgoutput",
        "slot.name": "keycloak_cdc_slot_minimal",
        "publication.name": "keycloak_cdc_publication_minimal",
        "publication.autocreate.mode": "filtered",
        "schema.include.list": "public",
        "table.include.list": "public.user_entity,public.credential,public.user_attribute",
        "include.schema.changes": "false",
        "tombstones.on.delete": "false",
        "heartbeat.interval.ms": "10000"
      }
    }
