apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-connect
resources:
  - namespace.yaml
  - connector-configmap.yaml
  - kafka_connect.yaml
  - middleware.yaml
  - ingress.yaml
