apiVersion: v1
kind: Secret
metadata:
  name: postgresql-keycloak-secret
  namespace: postgresql
type: Opaque
stringData:
  KEYCLOAK_DB: keycloak
  KEYCLOAK_DB_USER: keycloak
  KEYCLOAK_DB_PASSWORD: keycloak
