apiVersion: v1
kind: Secret
metadata:
  name: postgresql-camunda-secret
  namespace: postgresql
type: Opaque
stringData:
  CAMUNDA_DB: camunda
  CAMUNDA_DB_USER: camunda
  CAMUNDA_DB_PASSWORD: camunda
