apiVersion: v1
kind: Secret
metadata:
  name: postgresql-admin-secret
  namespace: postgresql
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

