apiVersion: v1
kind: Secret
metadata:
  name: postgresql-spicedb-secret
  namespace: postgresql
type: Opaque
stringData:
  SPICEDB_DB: spicedb
  SPICEDB_DB_USER: spicedb
  SPICEDB_DB_PASSWORD: spicedb
