apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - adminer
  - confluent
  - elasticsearch
  - grafana
  - kafka
  - kafka-connect
  - kcat
  - keycloak
  - mongodb
  - otel
  - postgresql
  - prometheus
  - redpanda
  #- spicedb

