apiVersion: v1
kind: Namespace
metadata:
  name: kafka

---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb

---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql

---
apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch

---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: v1
kind: Namespace
metadata:
  name: spicedb
  