apiVersion: v1
kind: Secret
metadata:
  name: my-gin-app-secrets
type: Opaque
data:
  QUARKUS_DATASOURCE_USERNAME: cG9zdGdyZXM= # base64-encoded "postgres"
  QUARKUS_DATASOURCE_PASSWORD: eW91cnBhc3N3b3Jk # base64-encoded "yourpassword"
  QUARKUS_MONGODB_CONNECTION_STRING: bW9uZ29kYjovL21vbmdvdXNlcjptb25nb3Bhc3N3b3JkQG1vbmdvLXNlcnZpY2U6MjcwMTcvbXlkYg== # base64-encoded "mongodb://mongouser:mongopassword@mongo-service:27017/mydb"