apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
<<<<<<< HEAD

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - ingress.yaml
=======
resources:
  - elasticsearch.yaml
>>>>>>> d9507493072f98322b3a48351889d3f6915c1605
