apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-index
  namespace: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui-index
  template:
    metadata:
      labels:
        app: webui-index
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          volumeMounts:
            - name: webui-index-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: webui-index-html
          configMap:
            name: webui-index-html
